### PR TITLE
feat: Create a 404 instant redirect to homepage

### PR DESCRIPTION
**Pull request by brianndiiri**

### CODE REVIEW

**Comment by alexiglesias93** [comment]
This solution shouldn't be `.js` based, there's a better option using HTML:
```html
<meta http-equiv="refresh" content="0; url=/" />
```

**Review by alexiglesias93 — CHANGES_REQUESTED** [review]
This solution shouldn't be `.js` based, there's a better option using HTML:
```html
<meta http-equiv="refresh" content="0; url=/" />
```

**Comment by brianndiiri** [comment]
@alexiglesias93 can I close this too? coz no JS needed?

**Comment by alexiglesias93** [comment]
Can we keep this hack?
Just add it in a `8.html` file.

**Review by alexiglesias93 — APPROVED** [review]

**Pull request merged**
